# Generated by Django 3.0.3 on 2020-03-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200319_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recommended_courses',
        ),
    ]
