# Generated by Django 3.0.3 on 2020-03-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_recommended_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='picture_src',
        ),
    ]
