# Generated by Django 3.0.3 on 2020-03-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_picture_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='interest_fields',
        ),
    ]
