# Generated by Django 3.0.3 on 2020-03-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200328_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='is_qualified',
        ),
    ]
