# Generated by Django 3.0.3 on 2020-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('course_src', models.URLField()),
                ('picture_src', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('create_date', models.DateField(blank=True, default=None)),
                ('training_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
