# Generated by Django 3.0.3 on 2020-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.CharField(default='replaceme', max_length=100),
            preserve_default=False,
        ),
    ]
